env:
  es2021: true
  node: true
extends:
  - airbnb-base
parserOptions:
  ecmaVersion: latest
  sourceType: module
overrides:
  - files: "*.test.js" 
    env: { "jest": true }
rules:
  no-console: 0
  indent: ["warn", 2]
  no-unused-vars: 1
  import/extensions:
    - error
    - ignorePackages
    - js: always
  no-underscore-dangle: [2, {"allow": ["__filename", "__dirname"]}]